### PR TITLE
fix#551, support struct as function param

### PR DESCRIPTION
**Pull request by liyue201**

### CODE REVIEW

**Comment by liyue201** [comment]
https://github.com/goplus/gop/issues/551#issue-679775080

**Comment by liyue201** [comment]
https://github.com/goplus/gop/issues/551#issue-679775080

**Comment by liyue201** [comment]
```go
package main

import (
	"fmt"
	"reflect"
)

type User struct {
	Name string
}

func main() {
	_type := reflect.TypeOf(User{})
	u1 := reflect.New(_type).Elem()
	fmt.Printf("u1.CanSet: %v\n", u1.CanSet())

	itf := u1.Interface()
	u2 := reflect.ValueOf(itf)
	fmt.Printf("u2.CanSet: %v\n", u2.CanSet())
}
```

ouput：
```
u1.CanSet: true
u2.CanSet: false
```

if the param is  an interface of a struct( not an interface of a pointer to a struct), the reflect.Value by calling reflect.ValueOf() is not addressable

**Comment by go-wyvern** [comment]
Your solution is not ideal. The parameters of the function are not necessarily obtained by loadVar. For example, the following example will call the loadField instruction to get the function parameters, 

```
type Obj struct {
	Bar string
}

type T struct {
	B Obj
}

func f(a Obj, bar string) {
	a.Bar = bar // panic Can’t Set Field
}

obj := Obj{
	Bar: "333",
}

t := T{
	B: obj,
}

f(t.B, "456")
```

**Comment by liyue201** [comment]
> Your solution is not ideal. The parameters of the function are not necessarily obtained by the instruction loadVar. For example, the following example will call the loadField instruction to get the function parameters,
> 

I modified the function `loadField`  to fix it .  I think we should clone  a new struct  as a function parameter.

**Comment by go-wyvern** [comment]
I think the way you modify it is not particularly good. There are many ways to obtain function parameters, not just loadVar and loadField, but also other instructions. The best way is to check the function parameters, form Stack, before the function is executed.

**Comment by liyue201** [comment]
i have another idea,  we can convert stackVar to execVar after calling the function

**Comment by liyue201** [comment]
#579

**Pull request closed without merging**
