### PR TITLE
support struct as a function param

### PR DESCRIPTION
**Pull request by liyue201**

### CODE REVIEW

**Comment by go-wyvern** [comment]
Whenever we load a variable in the stack, do we have to create a new variable? So if the structure is loaded multiple times, we will create multiple variables.
And the execution of the function should not be processed in the compile phase, it should be in the exec phase.

**Comment by liyue201** [comment]
execVar will only be created once because it has been replaced

**Comment by go-wyvern** [comment]
The problem is that before the bytecode function is executed, there is no copy non-reference type, so there is no need to modify the compile. Modifying the compile will cause an error in the builder of golang

**Comment by go-wyvern** [comment]
You can try to create a file to the testdata directory, then copy your test code into it, and then execute `gop go -test {goppath}` . Then you can catch this error

**Comment by liyue201** [comment]
i see.  太难了~~
```go
package main

import fmt "fmt"

type User struct {
	Name string
}

var u User

func main() {
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:12
	u = User{Name: "a"}
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:13
	f(u, "b")
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:14
	fmt.Println(u.Name)
}
func f(_arg_0 User, _arg_1 string) {
	var a User
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:5
	if !(_arg_1 != "") {
		goto _gop_1
	}
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:6
	a.Name, a = "c", _arg_0
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:5
	goto _gop_1
_gop_1:
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:8
	fmt.Printf(a.Name)
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:9
	a.Name = _arg_1
//line ./f:\code\go\mygop\exec\golang\testdata\29.struct\struct.gop:10
	fmt.Printf(a.Name)
}

```

**Pull request closed without merging**
