### PR TITLE
Range branch with label(break/continue/goto/return)

### PR DESCRIPTION
**Pull request by JessonChan**
```go
L:
for k, v := range [1,2,3] {
	if k < 2 {
		continue L
	}
	if k > 2{
                println("range break")
		break L
	}
	println(k, v)
}

```

### CODE REVIEW

**Comment by xushiwei** [comment]
It seems too complex to implement this feature.
Let's discuss how to improve it.

**Comment by JessonChan** [comment]
>  Let's discuss how to improve it.

Glad to discuss this.

**Comment by xushiwei** [comment]
In `cl` package we can introduce `ContainerTrait` and container `Iterator`:

```go
func TraitContainer(containerTy reflect.Type) ContainerTrait

type ContainerTrait struct {
    Key, Value reflect.Type
    Iter interface{} // func(c interface{}) Iterator or func(c interface{}) ValueIterator
}

type Iterator interface {
     Next() bool
     Key() interface{}
     Value() interface{}
}

type ValueIterator interface {
     Next() bool
     Key() reflect.Value
     Value() reflect.Value
}
```

And then

```go
for k, v = range container {
     ...
}
```

can become:

```go
trait := TraitContainer(reflect.TypeOf(container))
for __iter := trait.Iter(container); __iter.Next(); {
    k, v = __iter.Key().(trait.Key), __iter.Value().(trait.Value)
    ...
}
```

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/pull/563

**Comment by liyue201** [comment]
> In `cl` package we can introduce `ContainerTrait` and container `Iterator`:
> 
> ```go
> func TraitContainer(containerTy reflect.Type) ContainerTrait
> 
> type ContainerTrait struct {
>     Key, Value reflect.Type // Key can be nil, and it means the Iterator only has Value(), not has Key()
>     Iter interface{} // func(c interface{}) Iterator or func(c interface{}) ValueIterator
> }
> 
> type Iterator interface {
>      Next() bool
>      Key() interface{}
>      Value() interface{}
> }
> 
> type ValueIterator interface {
>      Next() bool
>      Key() reflect.Value
>      Value() reflect.Value
> }
> ```
> 
> And then
> 
> ```go
> for k, v = range container {
>      ...
> }
> ```
> 
> can become:
> 
> ```go
> trait := TraitContainer(reflect.TypeOf(container))
> for __iter := trait.Iter(container); __iter.Next(); {
>     k, v = __iter.Key().(trait.Key), __iter.Value().(trait.Value)
>     ...
> }
> ```

这个转化很巧妙，没看到这个帖子之前，光看代码一脸懵逼

**Pull request closed without merging**
