### PR TITLE
init condition fixed

### LINKED ISSUE #590: If-statement with init condition will not be coverted to golang correctly
```go
x:=1
if v:=x;v>0{
	println(v)
}
if v:=x+1;v>0{
	println(v)
}
```
the golang 

```go
package main

import fmt "fmt"

var (
	x int
	v int
	v int
)

func main() {
//line ./gg.gop:1
	x = 1
//line ./gg.gop:2
	v = x
//line ./gg.gop:2
	if !(v > 0) {
		goto _gop_1
	}
//line ./gg.gop:3
	fmt.Println(v)
//line ./gg.gop:2
	goto _gop_1
_gop_1:
//line ./gg.gop:5
	v = x + 1
//line ./gg.gop:5
	if !(v > 0) {
		goto _gop_2
	}
//line ./gg.gop:6
	fmt.Println(v)
//line ./gg.gop:5
	goto _gop_2
_gop_2:
}
```

### PR DESCRIPTION
**Pull request by JessonChan**
#590

### CODE REVIEW

**Comment by xushiwei** [comment]
This is a known issue. Because new block is expensive in exec/bytecode mode, so I think it is better if we only rewrite variable name. For the example in #590:

```go
var (
	x int
	v int
	v int
)
```

Can be changed to:

```go
var (
	x int
	v int
	v2 int
)
```

**Comment by JessonChan** [comment]
I think it's not only about the variable name, but also the variable scope and lifetime.
```go
if v := 1; v > 0 {
	if v := 2; v > 0 {
		println("inner", v)
	}
	println("outer", v)
}
```
this piece of code should coverted to be 
```go
package main

import fmt "fmt"

func main() {
	{
		var v int
//line ./if_cond.gop:1
		v = 1
//line ./if_cond.gop:1
		if !(v > 0) {
			goto _gop_1
		}
		{
			var v int
//line ./if_cond.gop:2
			v = 2
//line ./if_cond.gop:2
			if !(v > 0) {
				goto _gop_2
			}
//line ./if_cond.gop:3
			fmt.Println("inner", v)
//line ./if_cond.gop:2
			goto _gop_2
		_gop_2:
		}
//line ./if_cond.gop:5
		fmt.Println("outer", v)
//line ./if_cond.gop:1
		goto _gop_1
	_gop_1:
	}
}
```

**Comment by xushiwei** [comment]
> I think it's not only about the variable name, but also the variable scope and lifetime.

I see. But a new block scope is expensive. So I create a new block scope only when we have to do this. For example, when we are in a `for` statement.

**Comment by xushiwei** [comment]
Of course, we can implement Go+ just for work. All optimizations can be considered in next milestone.

**Comment by JessonChan** [comment]
Done is better than perfect. We can move faster.

**Pull request merged**
